### ISSUE TITLE
Question regarding `artifacts` folder

### ISSUE THREAD

**Issue by hongbo-miao** [mikejoh/cloud-provider-cloudlycke#2]
Hi @mikejoh, I [updated docker hub repository to my name](https://github.com/Hongbo-Miao/cloud-provider-cloudlycke/commit/934a63e3db100e659beda67f6ebd176e11c61df6), and published as a new image.

I have succeed running all 4 VMs.

![image](https://user-images.githubusercontent.com/3375461/149476692-f52f7607-e0e9-4323-b3d8-5735dbd2a618.png)

I saw in the README file:

> 3. When `ansible` and `vagrant` is done check the `artifacts/` directory, you should have two kubeconfigs there called `admin-master-c1-1.conf` and `admin-master-c2-1.conf`. Basically one for each Kubernetes cluster.

Does it mean that it will generate a folder called `artifacts` in the repo?
Hmm, I didn't see it generates any folder called `artifacts`. 

Thanks!

**Comment by Hongbo-Miao** [comment]
Add more info here for debugging. After ssh into one master node by

```sh
vagrant ssh master-c2-1
```

Here is the `admin.conf` file:

```
vagrant@master-c2-1:/etc/kubernetes$ sudo cat admin.conf
sudo cat admin.conf
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ERXhOREV3TXpjeE5Gb1hEVE15TURFeE1qRXdNemN4TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFF1CmMwTFhGb3orUm0wTk9CcEdTaCsvdzZBU2NocUlJODh0ZDNDMFNJNWtFZTRNL0FUL3JhL1QvOFB6aFlXOXpJNXoKa2ZCa0NObW15dmZtWERVaE5iR0VyY3BDRXF5akFEemNYTVJKdmQwWUk5Y3k5WFRFc3FzWUtrYWtlS1F4NndDSAo1VW9OejZSRURwZmZGNlJmOWZXYU42TG1HRnJ1dmdjK1o1SGFzcVIxbzJZYXlqUXc3RExvL3JtM0UzeFlnZ09SCjZBRWMzc2MzU2VGZGV5TXBmWWNTQytnMkpZZk5ydFc5NmV2Q29QU3N2WkNJbVFONUhTaGErUmxtaWtRejZnTnoKUDhRMElIOFdOeWQ3WTVDZWk3TGZKVnBINy9LRThta01UanEyR3hWN3dWeEgyUnRraFJYdGRDSTBDd2V5bmk0bQpaMldaY2pGSnhwMTlkUjdkVEFrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCSURTRHVOazE3bEZhMm9YMmt5ckhPd1dmUWIKKytmVTNFMVArL1IycUVmTVlQemtJbHRmZ0pjSWNYdml4dnJNM2tVa2VtemgzZzloV2VXZlF0eFpRZGtVaFh6MAppMVduR21QblNPU0pLRi9NUzBaV0F6alpkaGZ3bEdMMVp0cWpKeXRNVW5tckIvaU1DMVJuRHl3eUxXQ0ZVQWxNCjhKb1dMS2R6N1pFTmx6MjdOdkprQlllbmpGWThrem5oMHp1QmJhbVdwb3E4UXFCbnJjQ3krUFhNTnRMaUFaaFQKcFBYZXZIQ2tYMXJ5TDNTdWt3ZVU1UHJqZkNSVncwUnV1U2xpNnZnS2dSemhqYVlGRHhFY1dCZnFpbWNQNklxTQpyWmJ6LzZPWmZrU3VYdUtHTy9MZ0d2aGpld1d3SkxoRzZwckxMZkVVZkI3NVRmTjF0ZGNLMlVsRWwrUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.20.10:6443
  name: kubernetes-2
contexts:
- context:
    cluster: kubernetes-2
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes-2
current-context: kubernetes-admin@kubernetes-2
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJSStwYjlvY3oyVnN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBeE1UUXhNRE0zTVRSYUZ3MHlNekF4TVRReE1ETTNNVGRhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhwMWYyRWxKREdya0IxTzMKQTY1OHcwSlR6UkVxa2EwMDduUFFTVmRaQjMzSWtuZkRwc0NWek1PZHc4cXgxc28zWUhTSWhyclBDbVk1a1diMQpJTzJjMHMrSmV4ekxvblRFcWtDTE1VcXNtSHE4SVBoYldzSDAyU1J5UXgxMEFGbTVqeENGSE56WW1KV2VjM3p4CjBoL3dSOUUxNVgva3hsUDJPU1RpMEtXSm1WN1pjREtQakhWRXNTTVc5Qk93M3RQMVE4SUIrUjJVLzhqK2hSWVcKMHpqckJVL0lOQVJSM0pkQU4xbEhTcWFCRlFicktMbjNwUHJQdnFPS1R2cTZadXduWVN1L29lWTVqOGNXOWluSQpTcmtxcDlEMSt0bzBlRXJ3cXp0Rk13VGxNK1JENlBldWVHZlpkOHVZMnVOeWpmYi9vTHFKRmRUY1JQTW9JZThPCittSHdsUUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIeGZQYzdqTVhNRmVELzhiL1gxYmoyTWg1ZGNTQXFlanBNTQpXc0JmTlVZN3lST1lsbGtwQnoxcEptZGc0QVF0NlFnUzRZeUViZlM4eW9ldjhkcFdXRzNYNndYTkRBWVQzNnRzCmJRRFJnQWhEQlNhT01hUWo3T3FteGtXNnpmaStpSERGR0NMWWx6ZGdMT2VRd3ROSm8ySkFrU0ZLc1FOYkErdkIKMGlKd010TkxqZjBWeUEwVStRR0d5eUY4Y2pHdXJpamNoV1FtTDZlRGdwZTU2RURwU2t1citOQkU3T2t6QlFQTQp4c3hWcFJrWjhOeW10bEM0VWhEMU9yVUp1YWt4eG9kRXcyS3ZVNFpUUGRVWnd1ZmR1NytHRlBUOGtZdlVNZkpICng1cWJScHNCTndxdmNtb2Vka3NLSU1mK1JXRnBFU2ZhaGF3NjQyWGVBejNZMHdvVlpKVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeHAxZjJFbEpER3JrQjFPM0E2NTh3MEpUelJFcWthMDA3blBRU1ZkWkIzM0lrbmZECnBzQ1Z6TU9kdzhxeDFzbzNZSFNJaHJyUENtWTVrV2IxSU8yYzBzK0pleHpMb25URXFrQ0xNVXFzbUhxOElQaGIKV3NIMDJTUnlReDEwQUZtNWp4Q0ZITnpZbUpXZWMzengwaC93UjlFMTVYL2t4bFAyT1NUaTBLV0ptVjdaY0RLUApqSFZFc1NNVzlCT3czdFAxUThJQitSMlUvOGoraFJZVzB6anJCVS9JTkFSUjNKZEFOMWxIU3FhQkZRYnJLTG4zCnBQclB2cU9LVHZxNlp1d25ZU3Uvb2VZNWo4Y1c5aW5JU3JrcXA5RDErdG8wZUVyd3F6dEZNd1RsTStSRDZQZXUKZUdmWmQ4dVkydU55amZiL29McUpGZFRjUlBNb0llOE8rbUh3bFFJREFRQUJBb0lCQVFDeVhoTDlRcE4vdTE4ZAoxV2krdmF6K0Rrc0VGeTZMdFdtYjNCWnFSeStGTXNrMkFLaU0wTmUzRk5aU1IyNSszd3ZzYTd0UWcrUDhDdUlZCldzWTUxQ3JLaCtlSDBNeHdFVDJ0U0ZtNDRyOHVFTXR6TUplYVlpVnAvUGxBbk9yWWhidkhaNmFqelJJWHRnYWUKNE02clRsT1RxNmNqZkVBUWZNYmJldXpYUkZMV2tHcUNCVlE4OXdvdUVOU1BPSlNqV2lqWHVDRWt1Qlp5aE9ZUworVHJHMWIwYzROcWlOdnBaT1ZYSkd1TlViSGxoak1MbHYxaE1hc1E0R2dWWFQ0ckYySUdZZ0YxbVZocEdtM21DCkJwNFpuY1R4TUk0RXZKZjNJWU5ocTE4UTUrZUZGbFBweHZmZjJXUGlydUd0TzJGVlVUNVFoL0xMdkJ6ZCtRTmUKS3hoSFozWUJBb0dCQU5mdTBGZFFNbHBpUWllZCtGWjV2R1RFRytmRFpXeW55RURaTFl1M21SNnVFc1hPVmF1UwpjdFk1MDc5Z0FNZDNwS2pRRllDb1NXdXZNYUgweENqTGV3dDByU0tuRjc0MTI0Z0UxMjVlWk5ONm9FSjM1WDU0CmtSdXVzVXlSRFdYRWNrRXJoaWpkZ3hoN2RIZmpEMDArVmZlWnRLYzBPTm1rcVZ0UjFVN3pZdFhsQW9HQkFPdDMKNjI1Vm5TNk9wZWg3TFlqNGZ4bjQreVJaYzBmdGk0SUh4bUg2VWtuZ1Q4MC95QkR3MzFqQld1SzBWSmFuRUw3bwphYngrcFVkZ0U2ZDhRZ3Jya0loelc4R0ZvV3JXU3kzd3FQVzkvNE1oSUd0MWpEc0N5QloxejZwK3lxMThEUmg4CjBESmdVemVvNjU5ZDcyN0RtSFNlMlZQMnhVYlJtc1F2MVUvREV3VHhBb0dBRWEwK0p2ZXN0NU4xb1BLZ29zdWkKYllsVVUzdStjTStuYUErZlYrRzJ5amtyMWorVzZjMjZVdWsyK1dLdGphYXd0eFVadlllSlF5UjdacXUzNXpNSgpKcDN0a25tbFN1L3p3Y1hMc1FCUE5yVENLODdPM2JTWEJISWZsNG9FVThGcUxRV1lIUDVOUGhMVkxQOU1nR0ZLCi9sTDU0L28xY1RPMm5ZQXNleU1YZ3pVQ2dZQVBBOGVVY29zaVUrQktjY2hXaXBuNE93TXdyeStGcjZVTXRwZzAKMlRSMEY0U2ZMdWtBQTR3S2FkSDAwTkR3Qmxrd0F6dnkxQlNQOTVWcFFhZ29jQnI0U0hyYVhUNE14UHRvUTRkUwpuRG4xejUvMG1qdEY3QWg4UGlqdTAwVHpTUXpBdWZ6QXFabkUyOVdpaE9mbXBUeE1lM0NhUlFzUlYvNUpjazlrCjFhaVowUUtCZ0NyekpMRm5nKzZCTkN2RVVCYzNKb2ZndTBBVHJiT0lEOVEySGhmSHNYcExDcGZXWWxLalpObTkKa3ovTnR0WXM3RmpGUENEYXAvWjFQb25oRWVhaWFieDhyWlNiZXQ0TlgrRDR1VXp0YXY5dUVHT2licXFNcGYrNQpMQUVkejJTa1JOWFg3N0Z6OVl1SFVuWVN5di9BRUlZNDRZZmtLY0wvT1BhQzBzMFZTRmpjCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```
